import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/dist/client/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Pagina de Rotas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-Br">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className='flex justify-center gap-4 bg-slate-400'>
        <Link href={"/"} className='hover:text-blue-500'>Inicio</Link>
        <Link href={"/blog"} className='hover:text-blue-500'>Blog</Link>
        <Link href={"/users"} className='hover:text-blue-500'>Users</Link>
        </nav>
        
        {children}
      </body>
    </html>
  );
}
